[package]
name = "srp6"
version = "1.0.0-alpha.1"
authors = ["Sven Assmann <sven.assmann.it@gmail.com>"]
edition = "2018"
description = "A safe implementation of the secure remote password authentication and key-exchange protocol (SRP), SRP6a and legacy are as features available."

[dependencies]
thiserror = "1.0"
sha-1 = "0.9"
rand = "0.8"
num-bigint = { version = "0.4", features = ["rand"] }
num-traits = "0.2"
hex = "0.4"
hex-literal = "0.3"

[dev-dependencies]

[features]
legacy = []
default = []

