[package]
name = "chadehoc-srp6"
version = "0.1.0"
authors = [
    "Sven Assmann <sven.assmann.it@gmail.com>",
    "Chadehoc <1562517+Chadehoc@users.noreply.github.com>",
    # also Github user "valpaq"
]
edition = "2021"
description = "Implementation of the secure remote password authentication and key-exchange protocol SRP-6a"
license = "MIT"
include = ["src", "examples", "LICENSE", "README.md", "CHANGELOG.md"]

[dependencies]
crypto-bigint = { version = "0.6.0", features = ["rand", "alloc", "serde", "zeroize"] }
derive_more = { version = "2.0.1", features = ["error", "display"] }
hex-literal = "0.4.1"
num-traits = "0.2"
serde = { version = "1.0.217", features = ["derive"] }
sha1 = "0.10.1"
zeroize = { version = "1.8.1", features = ["zeroize_derive"] }

# fuzzing
arbitrary = { version = "1.4.1", optional = true, features = ["derive"] }

[dev-dependencies]
serde_json = "1.0.137"

[features]
# allow empirical micro-optimisation
emp = []
