[alias]
pedantic = [
    "clippy",
    "--all-features",
    "--",
    "-D", "missing_docs",
    "-D", "clippy::pedantic",
    "-A", "clippy::must_use_candidate",
    "-A", "clippy::doc_markdown",
    "-A", "clippy::cast_possible_truncation",
    "-A", "missing-docs",
    "-A", "clippy::missing_panics_doc",
    "-A", "clippy::missing_errors_doc",
    "-A", "clippy::needless_pass_by_value",
    "-A", "clippy::similar_names",
    "-D", "clippy::empty_structs_with_brackets",
    "-D", "clippy::empty_enum_variants_with_brackets",
    # "-W", "clippy::fn_to_numeric_cast_any", # faux positifs, mais à vérifier
    "-W", "clippy::allow_attributes_without_reason",
    "-W", "clippy::as_pointer_underscore",
    "-W", "clippy::assertions_on_result_states",
    "-W", "clippy::blocks_in_conditions",
    "-W", "clippy::clone_on_ref_ptr",
    "-W", "clippy::float_cmp_const",
    "-W", "clippy::infinite_loop",
    "-W", "clippy::large_include_file",
    "-W", "clippy::lossy_float_literal",
    "-W", "clippy::str_to_string",
    "-W", "clippy::string_slice",
    "-W", "clippy::todo",
    "-W", "clippy::unused_result_ok",
    "-W", "clippy::verbose_file_reads",
]